version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_rental_service
    restart: on-failure
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: rental_postgres_db
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}', '-d', '${POSTGRES_DB}']
      interval: 5s
      timeout: 2s
      retries: 10
    volumes:
      - ./database/sakila-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/sakila-data.sql:/docker-entrypoint-initdb.d/2-data.sql